src/authentication/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

src/pages/urls.py
from django.urls import path
from . import views

app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),
]

src/taches/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('todo.urls')),
    path('account/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'todo.views.error_404_view'
handler500 = 'todo.views.error_500_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/todo/urls.py
from django.urls import path
from . import views
from .views import TodoDetailView

app_name='todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add_todo'),
    path('detail/<int:pk>', TodoDetailView.as_view(), name='detail'),
]

src/authentication/models.py
from django.db import models
from django.contrib.auth.models import User

src/pages/models.py
from django.db import models

# Create your models here.

src/todo/models.py
from django.db import models

class Todo(models.Model):
    __tablename__ = 'todos'
    title = models.CharField(verbose_name='title', max_length=255)
    is_conpleted = models.BooleanField(verbose_name='completed', default=False)

    def __str__(self):
        return "{}".format(self.title)
    

src/todo/forms.py
from django import forms

class TodoForm(forms.Form):
    title = forms.CharField(label='Titre', max_length=255)

src/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

CRITICAL = 60

def register(request):
    if request.method == 'POST':
        form_data = request.POST

        first_name = form_data['first_name']
        last_name = form_data['last_name']
        username = form_data['username']
        email = form_data['email']
        password = form_data['password']
        confirm_password = form_data['password_confirm']

        subject = 'Account registration'
        message = f'''
            Hello {first_name} {last_name},
            Welcome, your account has been created.
        '''
        recipients = [email]

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.add_message(request, messages.ERROR, 'Username taken...')
                return redirect('/account/register/')
            elif User.objects.filter(email=email).exists():
                messages.add_message(request, messages.ERROR, 'Email taken...')
                return redirect('/account/register/')
            else:
                User.objects.create_user(first_name=first_name, 
                last_name=last_name, username=username, email=email, password=password)

        else:
            messages.add_message(request, messages.ERROR, 'Password not matching')
            return redirect('/account/register/')


        send_mail(subject=subject, message=message, recipient_list=recipients)
        messages.add_message(request, messages.SUCCESS, 'User registration successfully...')
        return HttpResponseRedirect('/')

    return render(request, 'authentication/register.html')



def login(request):
    if request.method=='POST':
        form_data = request.POST
        username = form_data['username']
        password = form_data['password']
        user = auth.authenticate(request, username=username, password=password)
        
        if user is not None:
            auth.login(request, user)
            messages.add_message(request, messages.INFO, 'Bienvenue vous etes connecté')
            return redirect('/')
        else:
            messages.add_message(request, CRITICAL, 'Username or password incorrect...')
            return HttpResponseRedirect('/account/login/')

    else:
        return render(request, 'authentication/login.html')


def logout(request):
    auth.logout(request)
    messages.add_message(request, messages.INFO, 'Merci, vous etes deconnecté...')
    return redirect('/')

src/pages/views.py
from django.shortcuts import render
from todo.models import Todo

def index(request):
    todos = Todo.objects.all()
    context ={
        'todos': todos
    }
    return render(request, 'pages/index.html', context)

src/todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .models import Todo
from .forms import TodoForm
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView
from django.views import View
from django.core.mail import send_mail, send_mass_mail, EmailMessage

# ERRORS PAGES
def error_404_view(request, exception):
    return render(request, 'errors/404.html')

def error_500_view(request):
    return render(request, 'errors/500.html')

def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'todo/index.html', context)



# def detail(request, question_id):
#     todo = Todo.objects.get(pk=)
class TodoDetailView(DetailView):
    model = Todo
    template_name='todo/detail.html'
    context_object_name='todo'
    
    def get_queryset(self):
        self.todo = get_object_or_404(Todo, pk=self.kwargs['pk'])
        return Todo.objects.filter(pk=self.todo.pk)
    

@login_required(login_url='/account/login')
def add(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        
        if form.is_valid():
            form_title = form.cleaned_data['title']
            todo = Todo()
            todo.title = form_title
            todo.save()

            subject = 'Todo created'
            message = f'''
            the user {request.user.username} has created a todo
        '''
            recipients = [request.user.email]
            from_email='sylvainka12@gmail.com'
            
            send_mail(subject=subject, message=message, from_email=from_email, recipient_list=recipients)
            return HttpResponseRedirect('/')


    form = TodoForm()
    return render(request, 'todo/add_todo.html', {'form': form})

src/templates/authentication/login.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock title %}


{% block content %}

    <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-12 m-md-auto m-lg-auto">
            <h1>Login</h1>
            <hr>

            {% if messages  %}

            {% for message in messages %}
                {% if message.tags == 'error' %}
                 <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>

                {% else %}

                 <div class="alert alert-{{ message.tags }}" role="alert">
                    {{message}}
                </div>
                {% endif %}
               
            
            {% endfor %}

            {% endif %}

            


            <form action="{% url 'account:login' %}" method='post'>

                {% csrf_token %}
                
                <div class="form-group">
                
                <label for="username">Username</label>
                    <input type="text" name="username" class='form-control'>
                </div>

              
                <div class="form-group">
                
                <label for="password">Password</label>
                    <input type="password" name="password" class='form-control'>
                </div>

                <button type='submit' class='btn btn-dark'>Se connecter</button>

            </form>


        </div>
    </div>
{% endblock content %}

src/templates/authentication/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock title %}


{% block content %}

    <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-12 m-md-auto m-lg-auto">
            <h1>Register</h1>
            <hr>

            {% if messages  %}

            {% for message in messages %}
                {% if message.tags == 'error' %}
                 <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>

                {% else %}

                 <div class="alert alert-{{ message.tags }}" role="alert">
                    {{message}}
                </div>
                {% endif %}
               
            
            {% endfor %}

            {% endif %}

            


            <form action="{% url 'account:register' %}" method='post'>

                {% csrf_token %}
                
                <div class="form-group">
                
                <label for="username">Username</label>
                    <input type="text" name="username" class='form-control'>
                </div>

                 
                <div class="form-group">
                
                <label for="first_name">First name</label>
                    <input type="text" name="first_name" class='form-control'>
                </div>

                 
                <div class="form-group">
                
                <label for="last_name">Last name</label>
                    <input type="text" name="last_name" class='form-control'>
                </div>

                 
                <div class="form-group">
                
                <label for="email">Email</label>
                    <input type="email" name="email" class='form-control'>
                </div>

                 
                <div class="form-group">
                
                <label for="password">Password</label>
                    <input type="password" name="password" class='form-control'>
                </div>

                 <div class="form-group">
                
                <label for="password">Confirm password</label>
                    <input type="password" name="password_confirm" class='form-control'>
                </div>

                <button type='submit' class='btn btn-dark'>Enregistrer</button>

            </form>


        </div>
    </div>
{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="X-Content-Type-Options=nosniff" http-equiv="Content-Type" />
    <title>Todo App | {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'shared/navbar.html' %}

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script type="text/js" src="{% static 'vendor/bootstrap/js/bootstap.min.js' %}"></script>
</body>
</html>

src/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}Bienvenue{% endblock title %}

{% block content %}
     
{% endblock content %}

src/templates/shared/navbar.html
<nav class="navbar navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'todos:index' %}">TodoApp</a>

<div class='d-flex justidy-content-between align-items-center'>
    {% if user.is_authenticated %}
    <a href="{% url 'todos:add_todo' %}" class='btn btn-outline-success mr-4'>Ajouter</a>
    <p class='mr-2 mt-2' style='color:#fff'>{{user.first_name}} {{user.last_name}}</p>
    <a href="{% url 'account:logout' %}" class='btn btn-outline-danger mr-2'>Logout</a>
    
    {% else %}
    <a href="{% url 'account:login' %}" class='btn btn-outline-primary mr-2'>Login</a>
   
    {% endif %}
    <a href="{% url 'account:register' %}" class='btn btn-primary'>Register</a>
    </div>
</nav>

src/templates/todo/add_todo.html
{% extends 'base.html' %}

{% block title %}Ajout de tâche{% endblock title %}


{% block content %}
<h1>Créer une nouvelle tâche</h1>

<form method='POST'>
{% csrf_token %}
{{ form}}

<button type='submit' class='btn btn-dark'>Envoyer</button>
</form>


{% endblock content %}

src/templates/todo/detail.html
{% extends 'base.html' %}

{% block title %}
todo detail
{% endblock title %}

{% block content %}
    <h2>{{todo.title}}</h2>

    <a href="{% url 'todos:index' %}"><=</a>
{% endblock content %}

src/templates/todo/edit_todo.html
{% extends 'base.html' %}

{% block title %}Edit todo{% endblock title %}

{% block content %}

<div class="row text-center">
    <div class="col-6 m-auto">
        <h1>Edit todo</h1>
        <hr>

         <form action="{% url 'todos:edit' id=todo.id %}" method='POST'>
        {% csrf_token %}
        <div class="form-group">
           <input type="text" value='{{ todo.title }}' placeholder='Title' class='form-control'>
        </div>
        <input type="submit" value='Submit' class='btn btn-sm btn-dark w-100'>
    </form>
    </div>
</div>

{% endblock content %}

src/templates/todo/index.html
{% extends 'base.html' %}

{% block title %}
Tâches
{% endblock title %}

{% block content %}

 <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-12 m-md-auto m-lg-auto">
                       {% if messages  %}

            {% for message in messages %}
                {% if message.tags == 'error' %}
                 <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>

                {% else %}

                 <div class="alert alert-{{ message.tags }}" role="alert">
                    {{message}}
                </div>
                {% endif %}
               
            
            {% endfor %}

            {% endif %}


                <ul class='list-group'>
                {% if todos %}
                        {% for todo in todos %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{todo.title}}
                            <div>
                                <a href="{% url 'todos:detail' pk=todo.pk %}" class='btn btn-sm btn-outline-info'>afficher</a>
                            </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
        </div>
</div>


    

{% endblock content %}